apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboothelloword-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboothelloword
  template:
    metadata:
      labels:
        app: springboothelloword
    spec:
      containers:
      - name: springboothelloword
        image: gcr.io/doantotnghiep-426507/springboothelloword:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboothelloword
spec:
  selector:
    app: springboothelloword
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalance
